### ISSUE TITLE
Why location permission?

### ISSUE THREAD

**Issue by tallero** [raghavk92/Kontroller#6]
Why the application requires location permissions?

**Comment by raghavk92** [comment]
https://getlief.zendesk.com/hc/en-us/articles/360007600233-Why-does-Android-require-Location-Permissions-for-Bluetooth-

"Unfortunately, Android 6.0 announced location permissions are required for Bluetooth scanning to work. See Android's official announcement here.

This requirement still continues today, in the most modern Android release. This is the latest Android specification.

Lief understands this is an unfortunate requirement of the Android OS, and we hope the requirement is lifted in future releases of the operating system. Sensibly, Bluetooth functionality should not be linked to Location Permissions or GPS."

**Comment by tallero** [comment]
When it is said "android P is required", you do mean that the phone has to ship with android p, right?

**Comment by raghavk92** [comment]
No, It doesnot have to ship with Android Pie. It only needs to have it (Either through an update or a Custom ROM).which device are you using. The app works on pixel 3 so it should work on yours too unless your device manufacturer has disabled this feature.

If it is disabled you are not alone. All one plus phones are disabled and many others too.

You can check if you device supports this BluetoothHID device profile . If it doesnt then ask your device manufacturer to fix it . Scold/Abuse them if you can.

You can check if this feature is enabled or not by using this app i made for this very purpose
https://play.google.com/store/apps/details?id=com.rkaneapplabs.bluetooth_hid.bluetoothproxy

**Comment by tallero** [comment]
lineageos 16 on titan (moto g 2014)
