### ISSUE TITLE
App not working on few devices

### ISSUE THREAD

**Issue by imMayankRaj** [raghavk92/Kontroller#7]
Thanks for this repo. This app seems to be working on some devices I have tried. But it didn't work on Lenovo Note K10. The app  shows device is connected by nothing works on target device. What can be the reason?

**Comment by raghavk92** [comment]
Many device manufacturers have disabled the Bluetooth HID device profile on their devices. You would have to ask your device manufacturers to enable it. You can check with this app {Bluetooth HID Device Profile Compatibility Checker} if the Bluetooth HID device profile is disabled for you or not.

**Comment by imMayankRaj** [comment]
I got that point. But does the HID profile needs to be enabled on both the devices, one which is controlling and also on the one which is being controlled?

**Comment by raghavk92** [comment]
Bluetooth HID device profile is for client devices that act as an HID device for another host device. For host devices its Bluetooth HID host profile I think. It has been there for a long time in android devices and windows/Ubuntu/Mac's have it. If you host device is able to connect to any Bluetooth mouse/keyboard then this app should work,Provided the controller has Bluetooth HID device profile enabled. You would need to open the app and try to connect the android device from the host device (Send pairing request from host device to controller while the app is open on the android device). Earlier pairings with the host device should be removed.
